plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6' apply false
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '8.0.0'
}

ext {
    set('springModulithVersion', "1.4.3")
    set('mybatisVersion', "3.0.3")
    set('mapstructVersion', "1.5.5.Final")
    set('springDotenvVersion', "4.0.0")
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'com.diffplug.spotless'
    apply plugin: 'checkstyle' // Plugin Checkstyle

    spotless {
        java {
            target 'src/**/*.java'
            googleJavaFormat()
            importOrder()
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }

    checkstyle {
        toolVersion = '12.1.0'
        configFile = rootProject.file('config/checkstyle/google_checks.xml')
        maxWarnings = 0
        configProperties = [
                'org.checkstyle.google.suppressionfilter.config': rootProject.file('config/checkstyle/checkstyle-suppressions.xml').absolutePath
        ]
    }

    group = 'com.uit'
    version = '1.0-SNAPSHOT'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    tasks.named("build") {
        dependsOn 'spotlessCheck'
    }
}