plugins {
    id 'java-library'
}

// Disable executable jar generation
bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    // Spring Core & Security
    api libs.spring.boot.starter
    api libs.bundles.spring.security.core
    api libs.spring.modulith.starter.core

    // Persistence
    api libs.bundles.mybatis.full

    // Mapping & Utilities
    api libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    api libs.commons.lang3


    // Azure Integration
    api libs.bundles.azure.integration

    // Security & JWT
    api libs.nimbus.jose.jwt

    // Messaging
    api libs.spring.boot.starter.amqp

    // Test dependencies
    testImplementation libs.mybatis.spring.boot.starter.test
    testImplementation libs.spring.modulith.starter.test
    testImplementation libs.spring.security.test
}
