spring.application.name=socius-webflux-app
server.port=8081

## Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.hikari.data-source-properties.timezone=Ho_Chi_Minh
spring.datasource.hikari.schema=${DB_SCHEMA}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## MyBatis Configuration
mybatis.mapper-locations=classpath*:mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# Azure Active Directory configuration
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${AZURE_TENANT_ID}
spring.cloud.azure.active-directory.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${AZURE_CLIENT_SECRET}

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.azure.client-id=${AZURE_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${AZURE_CLIENT_SECRET}
spring.security.oauth2.client.registration.azure.scope=openid,profile,email
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.azure.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Azure Entra External (CIAM) Provider Configuration
spring.security.oauth2.client.provider.azure.authorization-uri=https://${AZURE_TENANT_ID}.ciamlogin.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://${AZURE_TENANT_ID}.ciamlogin.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
spring.security.oauth2.client.provider.azure.jwk-set-uri=https://${AZURE_TENANT_ID}.ciamlogin.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
azure.domain.name=${AZURE_PRIMARY_DOMAIN}

#spring.security.oauth2.client.provider.azure.user-info-uri=https://graph.microsoft.com/v1.0/me
logging.level.com.example.azuretest=DEBUG
logging.level.org.springframework.security=DEBUG

# Resource Server JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AZURE_TENANT_ID}.ciamlogin.com/${AZURE_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://${AZURE_TENANT_ID}.ciamlogin.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
# i18n Configuration
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.web.locale=en
#RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=true
#Notification Queue Configuration
notification.exchange.name=notification.exchange
notification.queue.name=notification.queue
notification.routing.key=notification.routing.key
# Azure Key Vault Configuration
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${KEY_VAULT_ENDPOINT}
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true
spring.cloud.azure.keyvault.secret.property-source-enabled=true