plugins {
    id 'java'
}

description = 'socius-mvc-app'

dependencies {
    // Spring Core & Security
    implementation libs.spring.boot.starter
    implementation libs.bundles.spring.security.core
    implementation libs.spring.modulith.starter.core

    // Persistence
    implementation libs.bundles.mybatis.full

    // Mapping & Utilities
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.commons.lang3

    // File Processing
    implementation libs.tika.core

    // Azure Integration
    implementation libs.bundles.azure.integration

    // Security & JWT
    implementation libs.nimbus.jose.jwt

    // Messaging
    implementation libs.spring.boot.starter.amqp

    // Test dependencies
    testImplementation libs.mybatis.spring.boot.starter.test
    testImplementation libs.spring.modulith.starter.test
    testImplementation libs.spring.security.test

    // MVC specific
    implementation libs.bundles.spring.mvc

    // Log4j2 for logging
    implementation libs.spring.boot.starter.log4j2

    // Actuator for monitoring and management
    implementation libs.spring.boot.starter.actuator
}
