package com.uit.sociuscoremodules.role.repository;

import com.uit.sociuscoremodules.role.constants.RoleConstants;
import com.uit.sociuscoremodules.role.converter.RoleConverter;
import com.uit.sociuscoremodules.role.dto.PermissionDto;
import com.uit.sociuscoremodules.role.dto.PermissionQueryDto;
import com.uit.sociuscoremodules.role.dto.RoleDto;
import com.uit.sociuscoremodules.role.dto.ScopedPermissionDto;
import com.uit.sociuscoremodules.role.persistence.RoleMapper;
import com.uit.sociuscoremodules.shared.constants.CommonConstant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

/** Repository for Role entity. */
@Repository
@RequiredArgsConstructor
public class RoleRepository {

  /** MyBatis Mapper for Role entity. */
  private final RoleMapper roleMapper;

  /** Singleton instance of RoleConverter. */
  private final RoleConverter roleConverter;

  /**
   * Find a role by its code.
   *
   * @param roleCode the role code
   * @return the RoleDto
   */
  public RoleDto findByRoleCode(String roleCode) {
    return roleConverter.entityToDto(roleMapper.findByRoleCode(roleCode));
  }

  /**
   * Find all roles.
   *
   * @return list of all RoleDtos
   */
  public List<RoleDto> findAll() {
    return roleConverter.entitiesToDtos(roleMapper.findAll());
  }

  /**
   * Find roles by type.
   *
   * @param roleType the role type
   * @return list of RoleDtos matching the type
   */
  public List<RoleDto> findByRoleType(String roleType) {
    return roleConverter.entitiesToDtos(roleMapper.findByRoleType(roleType));
  }

  /**
   * Find permissions by client ID grouped by scope.
   *
   * @param clientId the client ID
   * @return list of scoped permissions
   */
  public List<ScopedPermissionDto> findPermissionsByClientIdGrouped(String clientId) {
    List<PermissionQueryDto> rawPermissions = roleMapper.findPermissionsByClientIdGrouped(clientId);
    return groupPermissionsByScope(rawPermissions);
  }

  /**
   * Group permissions by their scope using Java Streams.
   *
   * <p>This method organizes permissions into scoped groups based on role type and scope code. The
   * grouping key is generated by {@link #buildScopeKey} to uniquely identify each scope. The
   * display scope and scope code are taken from the first element of each grouped list for
   * presentation purposes.
   *
   * @param permissionDtos the list of PermissionQueryDto to be grouped
   * @return the list of ScopedPermissionDto grouped by scope
   */
  private List<ScopedPermissionDto> groupPermissionsByScope(
      List<PermissionQueryDto> permissionDtos) {

    return new ArrayList<>(
        permissionDtos.stream()
            .collect(
                Collectors.groupingBy(
                    dto -> buildScopeKey(dto.getRoleType(), dto.getRoleCode(), dto.getScopeCode()),
                    LinkedHashMap::new,
                    Collectors.collectingAndThen(
                        Collectors.toList(),
                        group -> {
                          PermissionQueryDto first = group.get(CommonConstant.INIT_INDEX);
                          return ScopedPermissionDto.builder()
                              .scope(first.getRoleType())
                              .scopeCode(first.getScopeCode())
                              .roleName(first.getRoleName())
                              .permissions(group.stream().map(this::buildPermissionDto).toList())
                              .build();
                        })))
            .values());
  }

  /**
   * Build a PermissionDto from a PermissionQueryDto.
   *
   * @param dto the permission query DTO containing permission details
   * @return the constructed PermissionDto
   */
  private PermissionDto buildPermissionDto(PermissionQueryDto dto) {
    return PermissionDto.builder()
        .permissionCode(dto.getPermissionCode())
        .permissionName(dto.getPermissionName())
        .resource(dto.getResource())
        .action(dto.getAction())
        .description(dto.getDescription())
        .build();
  }

  /**
   * Build a unique scope key for grouping permissions.
   *
   * <p>The scope key is used internally as a map key to group permissions that belong to the same
   * scope. It combines role type with either the scope code (for scoped roles) or role code (for
   * unscoped roles). This ensures that permissions are correctly grouped even when multiple roles
   * share the same type but different scopes.
   *
   * @param roleType the role type (e.g., "SYSTEM", "DEPARTMENT", "TEAM")
   * @param roleCode the role code
   * @param scopeCode the scope code (may be null for system-wide roles)
   * @return the constructed scope key in format "roleType:scopeCode" or "roleType:roleCode"
   */
  private String buildScopeKey(String roleType, String roleCode, String scopeCode) {
    return roleType
        + RoleConstants.SCOPE_KEY_SEPARATOR
        + (scopeCode != null ? scopeCode : roleCode);
  }
}
